### ISSUE TITLE
Can we get the requested route + params in shouldRoute()?

### ISSUE THREAD

**Issue by tstirrat** [pixelfusion/react-route-guard#3]
I would like to use route guards for detecting cached data and optionally loading it, would you consider accepting the requested route + params as a param to `shouldRoute()`?

I don't see any way to do this without injecting the router into the guard.

`ngrx/router`'s guards allow for something like this: https://github.com/ngrx/router/blob/master/docs/overview/guards.md

Here's how I'd like to use it:

```ts
interface MyParams {
  id: string;
}

class PlayerRouteGuard implements RouteGuard {
  constructor(private readonly store: Store<State>) {}

  shouldRoute(match: match<MyParams>): RouteGuardResultType {
    const state = getPlayersState(this.store.getState());
    const playerId = match.params.id;
    const player = getPlayerById(state, playerId);
    if (!player) {
      this.store.dispatch(loadPlayer(playerId));
    }
    return true;
  }
}
```

**Comment by tstirrat** [comment]
I wrote a mod to get this working, but there's an issue with re-entering the same route with different properties e.g. `/players/1` -> `/players/2` ... it won't run the guard a second time (`componentDidMount` is the trigger).

I suspect my use case is out of scope of this component. Perhaps you'd entertain the ability to check the guard each time props change (`componentWillRecieveProps`). Maybe this could be an optional `<SecureRoute>` param.

I'll keep modding and see how it goes.

edit: here is my mod including desired usage: tstirrat/pesleagues#47

**Comment by oniice** [comment]
> my use case is out of scope of this component. Perhaps you'd entertain the ability to check the guard each ti

@tstirrat did you ever get this sorted?

**Comment by tstirrat** [comment]
No, I changed to use `redux-little-router` instead
